import "./globals.scss";
import { GeistSans } from "geist/font/sans";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={GeistSans.className}>
			<body>{children}</body>
		</html>
	);
};
